// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djvydqlnpdmmcoxbgovv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqdnlkcWxucGRtbWNveGJnb3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3Mjk5NzIsImV4cCI6MjA3NDMwNTk3Mn0.9SQU3y4abmWletHH8MbOsYEJXhu3k7u9rtn7G_mZC64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});